### ISSUE TITLE
Local theme stylesheets don't load properly in directories under home page when using -link-styles

### ISSUE THREAD

**Issue by tomcam** [pococms/poco#52]
Home page:
```
---
theme: "pasteboard"
---
# Welcome to tmp

[down](down/index.html)

```
Page under home page:

File down/index.md
```
hello, world. This theme is incomplete.
```

Run with -link-styles:

```
poco -link-styles
```

Result: Page looks weird if it uses any local stylesheets.  Stylesheets on the web load fine for nested directories like `down` in this example, but local ones don't. The theme says something like:

```
stylesheets:
- "../../css/base.css"
```

But that means in the down subdirectory it needs to be rewritten as (I think):

```
stylesheets:
- "../../../css/base.css"
```

**Comment by pococms** [comment]
Removed the -link-styles flag!
