### ISSUE TITLE
Probable bug: aside, etc. in the front matter are looking in the home dir, not the document's current dir, for aside.md or whatever

### ISSUE THREAD

**Issue by tomcam** [pococms/poco#53]
Demonstrated website/docs/demos/informer.md, which has:

```
aside: "docs/demos/informer-aside.md"
```

When the user would just expect:

```
aside: "informer-aside.md"
```

**Comment by pococms** [comment]
Incorrect thank heavens

**Comment by tomcam** [comment]
Uh no it still seems to apply at least to `aside` which means it should be the same for all page layout files???

**Comment by pococms** [comment]
Man I need more sleep
